### ISSUE TITLE
[BUG]  offset's don't match. very strange.

### ISSUE THREAD

**Issue by DizzyIoeuy** [IwoRosiak/RimWorldHolsters#2] opened 2022-02-22 23:19 UTC
The editor for weapon position doesn't reflect the actual position once in game. Here's an image.
![mtch](https://user-images.githubusercontent.com/87795588/155236005-58566e3c-2618-48e1-afda-179149d7e4cd.png)

**Comment by IwoRosiak** [comment] 2022-02-23 10:11
Hi, the offset in the settings is correct. 0.75 on X-axis seems to be about right. Would you be able to send me your logs (there is a button in the console) as well as a screenshot of how it looks in the game?

Thanks a lot! <3

**Comment by DizzyIoeuy** [comment] 2022-02-24 00:29
[Player.log](https://github.com/IwoRosiak/RimWorldHolsters/files/8128728/Player.log)

The screenshot and how it looks in game is like above. Your position before I edit it is pretty much centered right. Just need a z adjustment for some views. But editing it is difficult because in the editor it looks off.

**Comment by kaedys** [comment] 2022-02-25 17:20
This appears to be a UI scale issue.  When my UI is set to 2x (because 4k monitor), the offset display in the settings is wildly off for all weapons.  When I set the UI scale to 1x, the offset display works as expected:
<img width="451" alt="F93EFGAbzR" src="https://user-images.githubusercontent.com/9020449/155758815-9fcfb752-3c58-4763-9aef-206d8f4fddb1.png">
<img width="903" alt="AztBGg9qN3" src="https://user-images.githubusercontent.com/9020449/155758819-6d20e701-4b5a-46b9-8ddf-c641a10f446f.png">

Edit: also, shifting around has resulted in the "zero" value instead having an extremely low non-zero value, likely due to floating point round-off error.  Recommend putting in logic where if the (absolute value) offset is below some threshold (0.001 seems fine, the offset in the settings is all +- 0.05), it overwrites it with 0.

**Comment by IwoRosiak** [comment] 2022-02-26 12:09
Ah, that makes sense! I will add options in the next update to compensate for the screen res :)

Regarding @kaedys suggestion, I have encountered this bug during testing :P seems it is very persistent since I thought I fixed it.

Thanks a lot guys and sorry it took so long for me to reply <3

**Comment by IwoRosiak** [comment] 2022-03-04 15:05
Hi guys, I have been unable to fix that issue :/ the problem is not that offsets do not match but that rotation is not calculated properly by the game itself after adjusting the UI scale. The issue can be fixed by turning down the UI scale to 1x. I know this is not the most optimal solution for you but I am unable to find a workaround for that :<

**Closed as completed** 2022-03-04 15:05 UTC
Labels: bug
